# -*- coding: utf-8 -*-
"""지도를 활용한 데이터 분석.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132j1SkeNoYk3ujGs2DD1oydqEVK5T3vA
"""

import folium
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

users = pd.read_csv('users.csv')

users

"""- folium
- leaflet.js 기반으로 만들어진 라이브러리
- 지도위에 경도, 위도 데이터를 활용해 표현하는 지도 시각화 라이브러리
"""

location_data = users[['id','latitude','longitude']]

using_data = users[users['country'] == 'South Korea'][['latitude','longitude']].drop_duplicates()

len(using_data)

#지도 띄우기, 부산 중심

map = folium.Map(location = [35.1796, 129.0756], zoom_start = 11)

map

for i, j in using_data.values[:1383]:
    popup = folium.Popup('1', max_width = 200)
    folium.Marker(location = [i, j] , popup = popup).add_to(map)

map

